export const navLinks = [
  { href: '/', label: 'Home' },
  { href: '/destinations', label: 'Destinations' },
  { href: '/experiences', label: 'Experiences' },
  { href: '/packages', label: 'Packages' },
  { href: '/about', label: 'About' },
  { href: '/testimonials', label: 'Testimonials' },
  { href: '/gallery', label: 'Gallery' },
  { href: '/contact', label: 'Contact' },
]

export const destinations = [
  {
    id: 'hunza',
    name: 'Hunza Valley',
    region: 'Gilgit-Baltistan',
    description: 'Experience the majestic beauty of Hunza Valley with its ancient forts, stunning glaciers, and warm hospitality.',
    price: 4200,
    rating: 4.9,
    duration: '7-10 Days',
    highlights: ['Ancient Forts', 'Glacier Views', 'Local Culture', 'Luxury Stays'],
  },
  {
    id: 'skardu',
    name: 'Skardu',
    region: 'Gilgit-Baltistan',
    description: 'Gateway to the world\'s highest peaks, offering breathtaking landscapes and adventure opportunities.',
    price: 3800,
    rating: 4.8,
    duration: '8-12 Days',
    highlights: ['K2 Base Camp', 'Shangrila Resort', 'Lake Saif-ul-Malook', 'Desert Trek'],
  },
  {
    id: 'fairy-meadows',
    name: 'Fairy Meadows',
    region: 'Gilgit-Baltistan',
    description: 'A paradise on earth with panoramic views of Nanga Parbat, the world\'s ninth highest mountain.',
    price: 3500,
    rating: 4.7,
    duration: '6-9 Days',
    highlights: ['Nanga Parbat', 'Camping', 'Trekking', 'Photography'],
  },
  {
    id: 'kashmir',
    name: 'Kashmir',
    region: 'Azad Jammu & Kashmir',
    description: 'The Switzerland of the East, featuring lush valleys, serene lakes, and Mughal gardens.',
    price: 3200,
    rating: 4.9,
    duration: '5-8 Days',
    highlights: ['Houseboats', 'Gardens', 'Skiing', 'Cultural Tours'],
  },
  {
    id: 'naran',
    name: 'Naran Kaghan',
    region: 'Khyber Pakhtunkhwa',
    description: 'Valley of fairies with stunning lakes, waterfalls, and mountain passes.',
    price: 2800,
    rating: 4.6,
    duration: '4-7 Days',
    highlights: ['Lake Saiful Muluk', 'Waterfalls', 'Trekking', 'Wildlife'],
  },
  {
    id: 'chitral',
    name: 'Chitral Valley',
    region: 'Khyber Pakhtunkhwa',
    description: 'Land of Kalash people, offering unique cultural experiences and natural beauty.',
    price: 3200,
    rating: 4.7,
    duration: '6-9 Days',
    highlights: ['Kalash Culture', 'Tirich Mir', 'Polo Festival', 'Hiking'],
  },
]

export const experiences = [
  {
    id: 'luxury-retreat',
    title: 'Luxury Mountain Retreat',
    description: 'Exclusive stays in premium resorts with private guides and bespoke activities.',
    price: 5000,
    duration: '7-10 Days',
    includes: ['Private Villa', 'Personal Guide', 'Helicopter Tour', 'Spa Treatments'],
  },
  {
    id: 'honeymoon',
    title: 'Honeymoon Paradise',
    description: 'Romantic getaways with private dinners, couples spa, and breathtaking views.',
    price: 6800,
    duration: '8-12 Days',
    includes: ['Private Suites', 'Romantic Dinners', 'Couples Spa', 'Photography'],
  },
  {
    id: 'corporate',
    title: 'Corporate Retreat',
    description: 'Team-building experiences in luxury settings with modern amenities.',
    price: 8500,
    duration: '5-7 Days',
    includes: ['Conference Facilities', 'Team Activities', 'Luxury Transport', 'Fine Dining'],
  },
  {
    id: 'adventure',
    title: 'Elite Adventure',
    description: 'For thrill-seekers: trekking, mountaineering, and extreme sports with expert guides.',
    price: 7500,
    duration: '10-14 Days',
    includes: ['Expert Guides', 'Premium Gear', 'Safety Team', 'Luxury Camping'],
  },
]

export const packages = [
  {
    id: 'gold',
    name: 'Gold Package',
    price: 3200,
    duration: '7 Days',
    description: 'Perfect for first-time luxury travelers',
    features: [
      '4-Star Accommodation',
      'Private Guide & Driver',
      'All Meals Included',
      'Sightseeing Tours',
      'Basic Photography',
      'Travel Insurance',
    ],
    highlighted: false,
  },
  {
    id: 'platinum',
    name: 'Platinum Package',
    price: 5800,
    duration: '10 Days',
    description: 'Our most popular premium experience',
    features: [
      '5-Star Luxury Hotels',
      'Private Helicopter Transfer',
      'Personal Concierge',
      'Fine Dining Experiences',
      'Professional Photography',
      'Spa Treatments (3 Sessions)',
      'Adventure Activities',
      'VIP Airport Services',
    ],
    highlighted: true,
  },
  {
    id: 'elite',
    name: 'Elite Package',
    price: 12500,
    duration: '14 Days',
    description: 'Ultimate bespoke luxury experience',
    features: [
      'Luxury Private Villas',
      '24/7 Personal Butler',
      'Helicopter Tours',
      'Michelin-Starred Chefs',
      'Film Production Team',
      'Unlimited Spa & Wellness',
      'Private Security Detail',
      'Custom Adventure Itinerary',
      'Luxury Gifts & Souvenirs',
    ],
    highlighted: false,
  },
]

export const testimonials = [
  {
    id: 1,
    name: 'Alexander Chen',
    role: 'CEO, TechVision Inc.',
    content: 'Northern Scapes transformed our corporate retreat into an unforgettable experience. The attention to detail was impeccable.',
    rating: 5,
    date: 'March 2024',
  },
  {
    id: 2,
    name: 'Sophia Williams',
    role: 'Luxury Travel Blogger',
    content: 'As someone who experiences luxury travel worldwide, I can confidently say Northern Scapes sets a new standard.',
    rating: 5,
    date: 'February 2024',
  },
  {
    id: 3,
    name: 'James & Maria Rodriguez',
    role: 'Honeymooners',
    content: 'Our honeymoon was pure magic. Every moment was perfectly curated. Thank you for the memories of a lifetime.',
    rating: 5,
    date: 'January 2024',
  },
]

export const trustBadges = [
  {
    id: 1,
    icon: 'shield',
    title: 'Premium Safety',
    description: 'VIP security and 24/7 medical support',
  },
  {
    id: 2,
    icon: 'globe',
    title: 'Global Network',
    description: 'International partnerships for seamless travel',
  },
  {
    id: 3,
    icon: 'star',
    title: 'Exclusive Access',
    description: 'Private locations and bespoke experiences',
  },
  {
    id: 4,
    icon: 'mountain',
    title: 'Expert Guides',
    description: 'Local specialists with decades of experience',
  },
]